services:
  web:
    build: .
    container_name: transporteprivado_web
    ports:
      - "8080:80"
    volumes:
      - "C:/transporteprivadomvc:/var/www/transporteprivadomvc"
    restart: unless-stopped