services:
  web:
    build: .
    container_name: transporteprivado_web_mvc
    ports:
      - "3000:80"
    volumes:
      - "C:/transporteprivadomvc:/var/www/transporteprivadomvc"
    restart: unless-stopped